project/cliente/urls.py
from django.urls import path
from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.home, name="index"),
    path("crear/", views.crear_cliente, name="crear-material"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),
    path('contacto', views.contacto, name="contacto")
]

project/producto/urls.py
from django.urls import path
from . import views

app_name = "producto"

urlpatterns = [
    path("", views.home, name="index"),
    path('crear/', views.crear_producto, name="crear-producto")
]

project/cliente/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nombre
    

class Idioma(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre=models.CharField(max_length=100)
    apellido=models.CharField(max_length=100)
    email=models.EmailField(max_length=100, null=True)
    nacimiento=models.DateField(null=True, blank=True)
    pais_origen=models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)
    idioma =models.ForeignKey(Idioma, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
    

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models


class Categoria(models.Model):
    nombre=models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    imagen=models.ImageField(null=True, blank=True)
    nombre=models.CharField(max_length=100)
    categoria=models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)
    precio=models.CharField(max_length=100)
    descripcion=models.CharField(max_length=300)
    stock=models.CharField(max_length=100)
    vendidos=models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

project/cliente/forms.py
from django import forms
from .models import Cliente, Pais, Idioma


class ClienteFormulario(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ['nombre', 'apellido', 'email','nacimiento', 'pais_origen', 'idioma']
        labels = {'nombre': 'Nombre', 'apellido': 'Apellido', 'email': 'Email','nacimiento': 'Nacimiento', 'pais': "Pais", 'idioma': 'Idioma'}
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellido': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'nacimiento': forms.TextInput(attrs={'class':'form-control'}),
            'pais_origen': forms.Select(attrs={'class':'form-control'}),
            'idioma': forms.Select(attrs={'class':'form-control'})
        }


class ClienteBuscarFormulario(forms.ModelForm):
    
    class Meta:
        model = Cliente
        fields = ['nombre']
        labels = {'nombre':''}
        widgets = {'nombre': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Buscar...'})}

project/producto/forms.py
from django import forms
from .models import Producto, Categoria



class ProductoFormulario(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ['imagen','nombre', 'categoria', 'precio','descripcion', 'stock', 'vendidos']
        labels = {'imagen':'Subir Foto','nombre': 'Nombre', 'categoria': 'Categoria', 'precio': 'Precio','descripcion': 'Descripcion', 'stock': "Stock", 'vendidos': 'Vendidos'}
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'categoria': forms.Select(attrs={'class':'form-control'}),
            'precio': forms.TextInput(attrs={'class':'form-control'}),
            'descripcion': forms.Textarea(attrs={'class':'form-control'}),
            'stock': forms.TextInput(attrs={'class':'form-control'}),
            'vendidos': forms.TextInput(attrs={'class':'form-control'})
        }

class ProductoBuscarFormulario(forms.ModelForm):
    
    class Meta:
        model = Producto
        fields = ['nombre']
        labels = {'nombre':''}
        widgets = {'nombre': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Buscar...'})}

project/cliente/views.py
from django.shortcuts import render
from . import models
from .forms import ClienteBuscarFormulario,ClienteFormulario

# Create your views here.
def home(request):
    if request.method == "GET":
        context = ClienteBuscarFormulario()
        clientes = models.Cliente.objects.all()
        return render(request,"cliente/index.html", {'form':context, 'clientes':clientes})
    else:
        form = ClienteBuscarFormulario(request.POST)
        if form.is_valid():
            context = ClienteBuscarFormulario()
            form = form.cleaned_data
            clientes = models.Cliente.objects.filter(nombre__contains=request.POST['nombre'])
            return render(request,"cliente/index.html", {'form':context, 'clientes':clientes})


def crear_cliente(request):
    if request.method == "GET":
        context = {"form":ClienteFormulario()}
        return render(request, "cliente/formulario_crear_cliente.html", context)
    else:
        form = ClienteFormulario(request.POST)
        if form.is_valid():
            form.save()
        context = {"form":ClienteFormulario()}
        return render(request, "cliente/formulario_crear_cliente.html", context)

project/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"core/index.html")

def contacto(request):
    return render(request, 'core/contacto_page.html')

project/producto/views.py
from django.shortcuts import render
from . import models
from .forms import ProductoFormulario, ProductoBuscarFormulario

# Create your views here.
def home(request):
    if request.method == "GET":
        context = ProductoBuscarFormulario()
        productos = models.Producto.objects.all()
        return render(request,"producto/index.html", {'form':context, 'productos':productos})
    else:
        form = ProductoBuscarFormulario(request.POST)
        if form.is_valid():
            context = ProductoBuscarFormulario()
            form = form.cleaned_data
            productos = models.Producto.objects.filter(nombre__contains=request.POST['nombre'])
            return render(request,"producto/index.html", {'form':context, 'productos':productos})


def crear_producto(request):
    if request.method == "GET":
        context = {"form":ProductoFormulario()}
        return render(request, "producto/formulario_crear_producto.html", context)
    else:
        form = ProductoFormulario(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
        context = {"form":ProductoFormulario()}
        return render(request, "producto/formulario_crear_producto.html", context)

project/cliente/templates/cliente/formulario_crear_cliente.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with titulo="Registrate como cliente" subtitulo="Complete el siguiente formulario" %}
{% endblock header %}

{% block contenido %}
<section class="bg-light py-5 border-bottom">
    <div class="container col-lg-6 col-xl-4">
    <form action="/cliente/crear" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>
    </div>
</section>
{% endblock contenido %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with titulo="Nuestros Clientes" buscador=True%}
{% endblock header %}

{% block contenido %}
    <section class="py-5 border-bottom mb-5">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                {% if clientes %}
                    {% for cliente in clientes %}
                        {% include 'core/card_cliente.html' with titulo=cliente.nombre apellido=cliente.apellido email=cliente.email nacimiento=cliente.nacimiento%}
                    {% endfor %}
                {% else %}
                        <section class="border-bottom">
                            <div class="container px-5 my-5 px-5">
                              <div class="text-center mb-5">
                                <h2 class="fw-bolder">Su busqueda no arrojo resultados...</h2>
                                <p class="lead mb-0">Intente con otros parametros su busqueda</p>
                              </div>
                              <div class="row gx-5 justify-content-center text-center">
                                <a href="{% url 'cliente:index' %}">Ver todo el listado</a>
                              </div>
                              </div>
                            </div>
                        </section>    
                {% endif %}
            </div>
        </div>
    </section>
{% endblock contenido%}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Pagina E-commerce Sanchez</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% include 'core/navbar.html' %}
    <!-- Header-->
    {% block header %} {% endblock header %}
    <!-- Features section-->
    {% block contenido %} {% endblock contenido %}
   
    <!-- Footer-->
    {% include 'core/footer.html' %}
    <!-- Bootstrap core JS-->
    {% include 'core/scripts.html' %}
  </body>
</html>

project/core/templates/core/card_cliente.html
<div class="card m-2" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{titulo}} {{apellido}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{nacimiento}}</h6>
    {% if email %}
      <p class="card-text">{{email}}</p>
      {% else %}
        <p class="card-text">No tiene email</p>
    {% endif %}
    <button class="btn btn-secondary disabled">Ver Perfil</button> 
  </div>
</div>

project/core/templates/core/card_producto.html
{% load static %}
<div class="col-lg-6 col-xl-4 mb-5">
    <div class="container card mb-5 mb-xl-0">
      <img src='/media/{{imagen}}' class="card-img-top mt-2" alt="Foto Producto" width="250" height="250"/>
      <div class="card-body p-5">
        <div class="small text-uppercase fw-bold">{{titulo}}</div>
        <div class="mb-3">
          <span class="display-4 fw-bold text-muted">${{precio}}</span>
        </div>
        <ul class="list-unstyled mb-4">
          <li class="mb-2">
            <i class="bi bi-check text-primary"></i>
            <strong>{{categoria}}</strong>
          </li>
          <li class="mb-2">
            <p>{{descripcion}}</p>
        </ul>
        <div class="d-grid"><a class="btn btn-outline-primary disabled" href="#!">Comprar</a></div>
      </div>
    </div>
  </div>

project/core/templates/core/contacto.html
<section>
    <div class="container px-5 my-5 px-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-6">
          <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <!-- Name input-->
            <div class="form-floating mb-3">
              <input
                class="form-control"
                id="name"
                type="text"
                placeholder="Enter your name..."
                data-sb-validations="required"
              />
              <label for="name">Nombre Completo</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">El nombre no es valido</div>
            </div>
            <!-- Email address input-->
            <div class="form-floating mb-3">
              <input
                class="form-control"
                id="email"
                type="email"
                placeholder="name@example.com"
                data-sb-validations="required,email"
              />
              <label for="email">Email</label>
              <div class="invalid-feedback" data-sb-feedback="email:required">Email campo requerido</div>
              <div class="invalid-feedback" data-sb-feedback="email:email">El email no es valido</div>
            </div>
            <!-- Phone number input-->
            <div class="form-floating mb-3">
              <input
                class="form-control"
                id="phone"
                type="tel"
                placeholder="(+54) 11-456-7890"
                data-sb-validations="required"
              />
              <label for="phone">Telefono</label>
              <div class="invalid-feedback" data-sb-feedback="phone:required">El telefono es requerido</div>
            </div>
            <!-- Message input-->
            <div class="form-floating mb-3">
              <textarea
                class="form-control"
                id="message"
                type="text"
                placeholder="Enter your message here..."
                style="height: 10rem"
                data-sb-validations="required"
              ></textarea>
              <label for="message">Mensage</label>
              <div class="invalid-feedback" data-sb-feedback="message:required">El mensaje es requerido</div>
            </div>
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
              <div class="text-center mb-3">
                <div class="fw-bolder">Form submission successful!</div>
                To activate this form, sign up at
                <br />
                <a href="https://startbootstrap.com/solution/contact-forms"
                  >https://startbootstrap.com/solution/contact-forms</a
                >
              </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage">
              <div class="text-center text-danger mb-3">Error sending message!</div>
            </div>
            <!-- Submit Button-->
            <div class="d-grid">
              <button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

project/core/templates/core/contacto_page.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with titulo="Contactanos" subtitulo="Contanos como podemos ayudarte en el siguiente formulario"%}
{% endblock header %}

{% block contenido %}
    {% include 'core/contacto.html' %}
{% endblock contenido %}

project/core/templates/core/footer.html
<footer class="py-5 bg-dark">
  <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023 - Desarrollo en Python by Matias Sanchez</p></div>
</footer>

project/core/templates/core/header.html
{% load static %}
<header  class="img-fluid bg-dark py-5" style="background-image: url('/static/core/assets/img/bg-masthead.jpg');background-size: auto">
  <div class="container px-5">
    <div class="row gx-5 justify-content-center">
      <div class="col-lg-6">
        <div class="text-center my-5">
          <h1 class="bg-light fw-bolder text-black mb-2 rounded p-2">{{titulo}}</h1>
          <p class="bg-dark rounded lead text-white-50 mb-4 p-2">{{subtitulo}}</p>
        </div>
        {% if buscador %}
          <div class="container">
            <form action="" class="d-flex justify-content-center flex-direction-row " method="POST">
              {% csrf_token %}
              {{form.as_p}}
                <div class="px-3">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </div>
            </form>
          </div>
      {% endif %}
      </div>
    </div>
  </div>
</header>

<!-- Bienvenidos a la 3° Entrega Python -->

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with titulo="Bienvenidos a la 3° Entrega Proyecto Final Python" %}   
{% endblock header %}

{% block contenido %}
    {% include 'core/testimonios.html' %}
{% endblock contenido %}

project/core/templates/core/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-5">
    <a class="navbar-brand" href="{% url 'core:index' %}">E-commerce</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'core:index' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'cliente:index' %}">Clientes</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'producto:index' %}">Productos</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'core:contacto' %}">Contacto</a></li>
      </ul>
    </div>
  </div>
</nav>

project/core/templates/core/scripts.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'core/js/scripts.js' %}"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

project/core/templates/core/testimonios.html
<!-- Testimonials section-->
<section class="py-5 border-bottom">
    <div class="container px-5 my-5 px-5">
      <div class="text-center mb-5">
        <h2 class="fw-bolder">Estamos Trabajando...</h2>
        <p class="lead mb-0">Estamos desarrolando el sitio para que puedas disfrutar de una experiencia unica</p>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-6">
          <!-- Testimonial 1-->
          <div class="card mb-4">
            <div class="card-body p-4">
              <div class="d-flex">
                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                <div class="ms-4">
                  <p class="mb-1">
                    Algunas secciones se encuentran en desarrollo, sepa disculparnos estamos trabajando para usted!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

project/producto/templates/producto/formulario_crear_producto.html
{% extends 'core/base.html' %}

{% block header %}
    {% include 'core/header.html' with titulo="Agregar Productos" subtitulo="Complete el siguiente formulario para guardar un producto" %}
{% endblock header %}

{% block contenido %}
<section class="bg-light py-5 border-bottom">
    <div class="container col-lg-6 col-xl-4">
    <form action="/producto/crear" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>
    </div>
</section>
{% endblock contenido %}

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
    {% include 'core/header.html' with titulo="Nuestros Productos" buscador=True %}
{% endblock header %}

{% block contenido %}
<section class="py-5 border-bottom">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            {% if productos %}
                {% for producto in productos %}
                    {% include 'core/card_producto.html' with titulo=producto.nombre descripcion=producto.descripcion precio=producto.precio imagen=producto.imagen %}
                {% endfor %}
            {% else %}
            <section class="border-bottom">
                <div class="container px-5 my-5 px-5">
                  <div class="text-center mb-5">
                    <h2 class="fw-bolder">Su busqueda no arrojo resultados...</h2>
                    <p class="lead mb-0">Intente con otros parametros su busqueda</p>
                  </div>
                  <div class="row gx-5 justify-content-center text-center">
                    <a href="{% url 'producto:index' %}">Ver todo el listado</a>
                  </div>
                  </div>
                </div>
              </section>
            {% endif %}
        </div>
    </div>
</section>
{% endblock contenido%}